import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
const buildId = (await readFile('.next/BUILD_ID', 'utf8')).trim();
async function walk(path) {
  const entries = await readdir(path, {withFileTypes: true});
  return (await Promise.all(entries.map(entry => entry.isDirectory() ? walk(join(path, entry.name)) : join(path, entry.name)))).flat();
}
const chunks = (await walk('.next/static')).filter(path => /\.(js|css|woff2)$/.test(path)).map(path => path.replace('.next/', '/_next/'));
const html=await readFile('.next/server/app/index.html','utf8');
const entryAssets=new Set([...html.matchAll(/\/_next\/static\/[^\s"<>\\]+?\.(?:js|css|woff2)/g)].map(m=>m[0]));
// Only the simple map's entry assets are precached. The optional 3D engine loads on demand.
const assets = ['/', '/manifest.webmanifest', '/icons/icon-192.png', ...chunks.filter(p=>entryAssets.has(p))];
await writeFile('public/offline-manifest.js', `// Generated by npm run build. Do not edit.\nself.DSB_BUILD = ${JSON.stringify(buildId)};\nself.DSB_ASSETS = ${JSON.stringify(assets)};\n`);
console.log(`Offline shell: ${assets.length} files, build ${buildId}`);
